### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by XciD** [Sroose/homebridge-loxone-ws#1]
Hello, 

Great work, I was supposed to make a PR to homebridge-loxone project with the support of WS but you was faster :D. I will use your project now :D

Maybe you could wait the merge of this PR https://github.com/alladdin/node-lox-ws-api/pull/2
to have access to direct events on UUID ?

**Comment by Sroose** [comment]
hello,

thanks!

I've added support for the new event names from the node-low-ws-api.
