### ISSUE TITLE
Plugin doesn't support multiple accessories with the same name.

### ISSUE THREAD

**Issue by DerFlash** [Sroose/homebridge-loxone-ws#11]
In the ItemFactory.js the parsed items are saved within the itemList using their name. So as soon as you name your Lamps just "Light" in Loxone (which should be fine since you've already sorted them by their room attribute), you'll only get one of them recognised by the Homebridge.

I've tried to use their uuid as a key or just add them by Array.push and changing the for-loop, but then I'll get an error and unfortunately I've no time to debug this yet:

Jun 29 13:36:45 raspberrypi homebridge[2703]: throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);

**Comment by DerFlash** [comment]
May be related to #10

**Comment by Sroose** [comment]
@DerFlash Thanks for the help! PR merged.
