### ISSUE TITLE
works incorrectly  after a while

### ISSUE THREAD

**Issue by zhooley** [Sroose/homebridge-loxone-ws#15]
Hi!

It works fine, but after a while I see my accessories state corectly if I turn the lamps manually on or off, but if I turn the lights off and on from the phone, their status changes only on the phone, the real device does not turn on or off.

After homebridge restart it works again for a while.

Any suggestion?

Thanks

**Comment by Nexus2k** [comment]
You need the newer version 1.0.3 incase you're running Loxone Firmware 9.x they changed the authentication scheme.

**Comment by Sroose** [comment]
Closing this, should be ok with latest version.
