### ISSUE TITLE
garagegate control

### ISSUE THREAD

**Issue by hihipto** [Sroose/homebridge-loxone-ws#25]
dear @Sroose , The home bridge is running fine in a container on my synology! Thanks for that! 
Would it be possible to add the garage gate control (which is similar to the blinds?)[https://www.loxone.com/enen/kb/garagegate/](url)

**Comment by Sroose** [comment]
Added in release 1.0.5
Thanks to @dgburton !

I did not test this myself, so let me know if it's working fine for you.

**Comment by hihipto** [comment]
@Sroose it is working great 😄
