### ISSUE TITLE
No actual responses from loxone miniserver

### ISSUE THREAD

**Issue by koraysels** [Sroose/homebridge-loxone-ws#26]
I have everything up and running and all my accesories are loaded in the home app on my phone and when I press a switch it does say it send a signal but it doesn't do anything .. the only thing that works is the temperature sensor value... It seems like all signals are sent to the miniserver but they don't get processed by loxone correctly ? 

I have v 1.0.2 because v1.0.4 does not work on my RPi... it has errors with WS-API

**Comment by Nexus2k** [comment]
https://github.com/Sroose/homebridge-loxone-ws/pull/28 will fix this issue. The error with the WS-API came from the DimmerItem that tried to query the ItemState before the connection was established.

**Comment by Sroose** [comment]
#28 included in release 1.0.5
Thanks @Nexus2k !
