### ISSUE TITLE
Adding KNX devices

### ISSUE THREAD

**Issue by marc252** [Sroose/homebridge-loxone-ws#30]
Hi, I would like to add my knx accessories in my loxone miniserver to be controlled by homebridge, right now it detects them at boot but won't parse them correctly:
[Loxone] Platform - The widget 'Sala Estar 1 in Sala d'estar' of type UpDownDigital is an item not handled.

In this case its a window blinder, do I have to write my own type?
Can someone point out where should I start looking?
P.D. I can control this devices via http GET queries but no idea how to integrate them in the plugin

**Comment by LLPP65** [comment]
I had the same issue and had to modify ItemFactory.js to set the type based on names:

For example:

    if (item.name.includes('Persiana')) {
        item.type = "Jalousie";
    }
    if (item.name.includes('Estor')) {
        item.type = "Jalousie";
    }

Saludos,
Len

**Comment by marc252** [comment]
Hi Len, thank's for the tip, now they get detected but it's not working, I think Jalousie is not the right type for KNX Blinders, I can see it's sending the command "ManualPosition/100" which I guess doesn't make sense for a UpDownDigital that expects a "UPOn" or "DownOn". Is there an appropiate type for "UpDownDigital"?

**Comment by LLPP65** [comment]
Marc,

You're right, I had forgotten. My blinds are also KNX blinds and I had to change the actual commands sent from homebridge-loxone-ws. Its'a bit of a hack, but now my blinds work.

/usr/lib/node_modules/homebridge-loxone-ws/items$ diff BlindsItem.js BlindsItem.js-dist 
140,145c140,144
< 
<     if (value  == 100){
<         command = 'UpOn';
<     }
<     if (value == 0) {
<         command = 'DownOn';
---
>     if (typeof value === 'boolean') {
>         command = value ? 'FullUp' : 'FullDown';
>     } else {
>         //reverse again the value
>         command = "ManualPosition/" + (100 - value);
147,155d145
< 
< 
< //    if (typeof value === 'boolean') {
< //        command = value ? 'FullUp' : 'FullDown';
< //    } else {
< //        //reverse again the value
< //        command = "ManualPosition/" + (100 - value);
< //    }
<

**Comment by marc252** [comment]
Thank's again Len, works great!!
If I have the time and patitente I'll try to contribute with a new Item definition for UpDownDigital.

**Comment by hihipto** [comment]
@Sroose 
will this "hack" be implemented in the code?
