### ISSUE TITLE
limit of 100 accessories 

### ISSUE THREAD

**Issue by zhooley** [Sroose/homebridge-loxone-ws#9]
100 items HomeKit has a limit of 100 accessories per bridge. If you have a large Loxone setup, try to filter unneeded items out either through Loxone access.

How to do this? In the Loxone Config?

**Comment by Sroose** [comment]
Hi @zhooley,
I'd advice to create a separate user in loxone config, then give that user access to only the needed peripherals
https://www.loxone.com/enen/kb/users-groups/

Alternatively you can Add filters in the itemfactory,checkCustomAttrs function.
